//
// Created by Juan Pablo Martínez Brenes on 8/30/18.
//

#ifndef ALGORITMOSDEBUSQUEDA_BUSQUEDASECUENCIAL_H
#define ALGORITMOSDEBUSQUEDA_BUSQUEDASECUENCIAL_H


#endif //ALGORITMOSDEBUSQUEDA_BUSQUEDASECUENCIAL_H
